// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiv1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApprovalDecisionDecision.
const (
	Approved ApprovalDecisionDecision = "approved"
	Rejected ApprovalDecisionDecision = "rejected"
)

// Valid indicates whether the value is a known member of the ApprovalDecisionDecision enum.
func (e ApprovalDecisionDecision) Valid() bool {
	switch e {
	case Approved:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for CanvasProjectionLayout.
const (
	CanvasProjectionLayoutFlex    CanvasProjectionLayout = "flex"
	CanvasProjectionLayoutGrid2x2 CanvasProjectionLayout = "grid-2x2"
	CanvasProjectionLayoutGrid3x2 CanvasProjectionLayout = "grid-3x2"
)

// Valid indicates whether the value is a known member of the CanvasProjectionLayout enum.
func (e CanvasProjectionLayout) Valid() bool {
	switch e {
	case CanvasProjectionLayoutFlex:
		return true
	case CanvasProjectionLayoutGrid2x2:
		return true
	case CanvasProjectionLayoutGrid3x2:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityName.
const (
	CapabilityNameAgent        CapabilityName = "agent"
	CapabilityNameCanvas       CapabilityName = "canvas"
	CapabilityNameGrafanaRead  CapabilityName = "grafana_read"
	CapabilityNameGrafanaWrite CapabilityName = "grafana_write"
	CapabilityNameKnowledge    CapabilityName = "knowledge"
	CapabilityNamePlaybook     CapabilityName = "playbook"
)

// Valid indicates whether the value is a known member of the CapabilityName enum.
func (e CapabilityName) Valid() bool {
	switch e {
	case CapabilityNameAgent:
		return true
	case CapabilityNameCanvas:
		return true
	case CapabilityNameGrafanaRead:
		return true
	case CapabilityNameGrafanaWrite:
		return true
	case CapabilityNameKnowledge:
		return true
	case CapabilityNamePlaybook:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityStatus.
const (
	Available   CapabilityStatus = "available"
	Degraded    CapabilityStatus = "degraded"
	Unavailable CapabilityStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the CapabilityStatus enum.
func (e CapabilityStatus) Valid() bool {
	switch e {
	case Available:
		return true
	case Degraded:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for ChartDefinitionVisualization.
const (
	Timeseries ChartDefinitionVisualization = "timeseries"
)

// Valid indicates whether the value is a known member of the ChartDefinitionVisualization enum.
func (e ChartDefinitionVisualization) Valid() bool {
	switch e {
	case Timeseries:
		return true
	default:
		return false
	}
}

// Defines values for DocumentStatus.
const (
	DocumentStatusDisabled DocumentStatus = "disabled"
	DocumentStatusFailed   DocumentStatus = "failed"
	DocumentStatusIndexing DocumentStatus = "indexing"
	DocumentStatusPending  DocumentStatus = "pending"
	DocumentStatusReady    DocumentStatus = "ready"
)

// Valid indicates whether the value is a known member of the DocumentStatus enum.
func (e DocumentStatus) Valid() bool {
	switch e {
	case DocumentStatusDisabled:
		return true
	case DocumentStatusFailed:
		return true
	case DocumentStatusIndexing:
		return true
	case DocumentStatusPending:
		return true
	case DocumentStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for KnowledgeBaseStatus.
const (
	KnowledgeBaseStatusActive   KnowledgeBaseStatus = "active"
	KnowledgeBaseStatusDisabled KnowledgeBaseStatus = "disabled"
)

// Valid indicates whether the value is a known member of the KnowledgeBaseStatus enum.
func (e KnowledgeBaseStatus) Valid() bool {
	switch e {
	case KnowledgeBaseStatusActive:
		return true
	case KnowledgeBaseStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	Tool      MessageRole = "tool"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookStatus.
const (
	PlaybookStatusActive   PlaybookStatus = "active"
	PlaybookStatusDisabled PlaybookStatus = "disabled"
)

// Valid indicates whether the value is a known member of the PlaybookStatus enum.
func (e PlaybookStatus) Valid() bool {
	switch e {
	case PlaybookStatusActive:
		return true
	case PlaybookStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookApprovalDecisionDecision.
const (
	Approve PlaybookApprovalDecisionDecision = "approve"
	Reject  PlaybookApprovalDecisionDecision = "reject"
	Rewind  PlaybookApprovalDecisionDecision = "rewind"
)

// Valid indicates whether the value is a known member of the PlaybookApprovalDecisionDecision enum.
func (e PlaybookApprovalDecisionDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Reject:
		return true
	case Rewind:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookRunStatus.
const (
	PlaybookRunStatusCancelled          PlaybookRunStatus = "cancelled"
	PlaybookRunStatusFailed             PlaybookRunStatus = "failed"
	PlaybookRunStatusQueued             PlaybookRunStatus = "queued"
	PlaybookRunStatusRunning            PlaybookRunStatus = "running"
	PlaybookRunStatusSucceeded          PlaybookRunStatus = "succeeded"
	PlaybookRunStatusWaitingForApproval PlaybookRunStatus = "waiting_for_approval"
	PlaybookRunStatusWaitingForInput    PlaybookRunStatus = "waiting_for_input"
)

// Valid indicates whether the value is a known member of the PlaybookRunStatus enum.
func (e PlaybookRunStatus) Valid() bool {
	switch e {
	case PlaybookRunStatusCancelled:
		return true
	case PlaybookRunStatusFailed:
		return true
	case PlaybookRunStatusQueued:
		return true
	case PlaybookRunStatusRunning:
		return true
	case PlaybookRunStatusSucceeded:
		return true
	case PlaybookRunStatusWaitingForApproval:
		return true
	case PlaybookRunStatusWaitingForInput:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookStepStatus.
const (
	PlaybookStepStatusCancelled          PlaybookStepStatus = "cancelled"
	PlaybookStepStatusFailed             PlaybookStepStatus = "failed"
	PlaybookStepStatusQueued             PlaybookStepStatus = "queued"
	PlaybookStepStatusRunning            PlaybookStepStatus = "running"
	PlaybookStepStatusSucceeded          PlaybookStepStatus = "succeeded"
	PlaybookStepStatusWaitingForApproval PlaybookStepStatus = "waiting_for_approval"
	PlaybookStepStatusWaitingForInput    PlaybookStepStatus = "waiting_for_input"
)

// Valid indicates whether the value is a known member of the PlaybookStepStatus enum.
func (e PlaybookStepStatus) Valid() bool {
	switch e {
	case PlaybookStepStatusCancelled:
		return true
	case PlaybookStepStatusFailed:
		return true
	case PlaybookStepStatusQueued:
		return true
	case PlaybookStepStatusRunning:
		return true
	case PlaybookStepStatusSucceeded:
		return true
	case PlaybookStepStatusWaitingForApproval:
		return true
	case PlaybookStepStatusWaitingForInput:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookSummaryStatus.
const (
	PlaybookSummaryStatusActive   PlaybookSummaryStatus = "active"
	PlaybookSummaryStatusDisabled PlaybookSummaryStatus = "disabled"
)

// Valid indicates whether the value is a known member of the PlaybookSummaryStatus enum.
func (e PlaybookSummaryStatus) Valid() bool {
	switch e {
	case PlaybookSummaryStatusActive:
		return true
	case PlaybookSummaryStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	CapabilityUnavailable ProblemCode = "capability_unavailable"
	Conflict              ProblemCode = "conflict"
	Forbidden             ProblemCode = "forbidden"
	Internal              ProblemCode = "internal"
	InvalidArgument       ProblemCode = "invalid_argument"
	NotFound              ProblemCode = "not_found"
	ProviderResultUnknown ProblemCode = "provider_result_unknown"
	ProviderTimeout       ProblemCode = "provider_timeout"
	ProviderUnavailable   ProblemCode = "provider_unavailable"
	Unauthenticated       ProblemCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case CapabilityUnavailable:
		return true
	case Conflict:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case InvalidArgument:
		return true
	case NotFound:
		return true
	case ProviderResultUnknown:
		return true
	case ProviderTimeout:
		return true
	case ProviderUnavailable:
		return true
	case Unauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusActive   SessionStatus = "active"
	SessionStatusArchived SessionStatus = "archived"
	SessionStatusBusy     SessionStatus = "busy"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusActive:
		return true
	case SessionStatusArchived:
		return true
	case SessionStatusBusy:
		return true
	default:
		return false
	}
}

// Defines values for UpdateCanvasRequestLayout.
const (
	UpdateCanvasRequestLayoutFlex    UpdateCanvasRequestLayout = "flex"
	UpdateCanvasRequestLayoutGrid2x2 UpdateCanvasRequestLayout = "grid-2x2"
	UpdateCanvasRequestLayoutGrid3x2 UpdateCanvasRequestLayout = "grid-3x2"
)

// Valid indicates whether the value is a known member of the UpdateCanvasRequestLayout enum.
func (e UpdateCanvasRequestLayout) Valid() bool {
	switch e {
	case UpdateCanvasRequestLayoutFlex:
		return true
	case UpdateCanvasRequestLayoutGrid2x2:
		return true
	case UpdateCanvasRequestLayoutGrid3x2:
		return true
	default:
		return false
	}
}

// Defines values for UpdateKnowledgeBaseRequestStatus.
const (
	UpdateKnowledgeBaseRequestStatusActive   UpdateKnowledgeBaseRequestStatus = "active"
	UpdateKnowledgeBaseRequestStatusDisabled UpdateKnowledgeBaseRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateKnowledgeBaseRequestStatus enum.
func (e UpdateKnowledgeBaseRequestStatus) Valid() bool {
	switch e {
	case UpdateKnowledgeBaseRequestStatusActive:
		return true
	case UpdateKnowledgeBaseRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for UpdateSessionRequestStatus.
const (
	UpdateSessionRequestStatusActive   UpdateSessionRequestStatus = "active"
	UpdateSessionRequestStatusArchived UpdateSessionRequestStatus = "archived"
)

// Valid indicates whether the value is a known member of the UpdateSessionRequestStatus enum.
func (e UpdateSessionRequestStatus) Valid() bool {
	switch e {
	case UpdateSessionRequestStatusActive:
		return true
	case UpdateSessionRequestStatusArchived:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatusFilter.
const (
	SessionStatusFilterActive   SessionStatusFilter = "active"
	SessionStatusFilterArchived SessionStatusFilter = "archived"
)

// Valid indicates whether the value is a known member of the SessionStatusFilter enum.
func (e SessionStatusFilter) Valid() bool {
	switch e {
	case SessionStatusFilterActive:
		return true
	case SessionStatusFilterArchived:
		return true
	default:
		return false
	}
}

// Defines values for ListSessionsParamsStatus.
const (
	ListSessionsParamsStatusActive   ListSessionsParamsStatus = "active"
	ListSessionsParamsStatusArchived ListSessionsParamsStatus = "archived"
)

// Valid indicates whether the value is a known member of the ListSessionsParamsStatus enum.
func (e ListSessionsParamsStatus) Valid() bool {
	switch e {
	case ListSessionsParamsStatusActive:
		return true
	case ListSessionsParamsStatusArchived:
		return true
	default:
		return false
	}
}

// ApprovalDecision defines model for ApprovalDecision.
type ApprovalDecision struct {
	Decision ApprovalDecisionDecision `json:"decision"`
	Reason   *string                  `json:"reason,omitempty"`
}

// ApprovalDecisionDecision defines model for ApprovalDecision.Decision.
type ApprovalDecisionDecision string

// Artifact defines model for Artifact.
type Artifact struct {
	MediaType string `json:"media_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
}

// ArtifactPreview defines model for ArtifactPreview.
type ArtifactPreview struct {
	MediaType string `json:"media_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
	Text      string `json:"text"`
	Truncated bool   `json:"truncated"`
}

// BusinessID defines model for BusinessID.
type BusinessID = string

// CanvasItem defines model for CanvasItem.
type CanvasItem struct {
	Chart    ChartDefinition `json:"chart"`
	Position int             `json:"position"`
}

// CanvasProjection defines model for CanvasProjection.
type CanvasProjection struct {
	ActiveChartId *BusinessID            `json:"active_chart_id"`
	CreatedAt     *time.Time             `json:"created_at,omitempty"`
	Items         []CanvasItem           `json:"items"`
	Layout        CanvasProjectionLayout `json:"layout"`
	Revision      int64                  `json:"revision"`
	SessionId     BusinessID             `json:"session_id"`
	UpdatedAt     *time.Time             `json:"updated_at,omitempty"`
	Visible       bool                   `json:"visible"`
}

// CanvasProjectionLayout defines model for CanvasProjection.Layout.
type CanvasProjectionLayout string

// Capability defines model for Capability.
type Capability struct {
	Name   CapabilityName   `json:"name"`
	Reason *string          `json:"reason,omitempty"`
	Status CapabilityStatus `json:"status"`
}

// CapabilityName defines model for Capability.Name.
type CapabilityName string

// CapabilityStatus defines model for Capability.Status.
type CapabilityStatus string

// CapabilityList defines model for CapabilityList.
type CapabilityList struct {
	Items []Capability `json:"items"`
}

// ChartDefinition defines model for ChartDefinition.
type ChartDefinition struct {
	CreatedAt     time.Time                    `json:"created_at"`
	Description   string                       `json:"description"`
	Id            BusinessID                   `json:"id"`
	Query         QueryDefinition              `json:"query"`
	Revision      int64                        `json:"revision"`
	Title         string                       `json:"title"`
	UpdatedAt     time.Time                    `json:"updated_at"`
	Visualization ChartDefinitionVisualization `json:"visualization"`
	VizConfig     map[string]interface{}       `json:"viz_config"`
}

// ChartDefinitionVisualization defines model for ChartDefinition.Visualization.
type ChartDefinitionVisualization string

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	MediaType string    `json:"media_type"`
	Name      string    `json:"name"`
	Service   *string   `json:"service,omitempty"`
	Tags      *[]string `json:"tags,omitempty"`

	// UploadToken Short-lived Aegis upload token; never a Provider credential.
	UploadToken string `json:"upload_token"`
}

// CreateKnowledgeBaseRequest defines model for CreateKnowledgeBaseRequest.
type CreateKnowledgeBaseRequest struct {
	FolderUid string `json:"folder_uid"`
	Name      string `json:"name"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// FolderUid Request authorization context only; it is not persisted as Session state.
	FolderUid *string `json:"folder_uid,omitempty"`
	Title     string  `json:"title"`
}

// Document defines model for Document.
type Document struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FailureReason Sanitized parsing failure suitable for display.
	FailureReason   *string        `json:"failure_reason,omitempty"`
	Id              BusinessID     `json:"id"`
	KnowledgeBaseId BusinessID     `json:"knowledge_base_id"`
	MediaType       string         `json:"media_type"`
	Name            string         `json:"name"`
	Service         string         `json:"service"`
	Size            int64          `json:"size"`
	Status          DocumentStatus `json:"status"`
	Tags            []string       `json:"tags"`
	UpdatedAt       *time.Time     `json:"updated_at,omitempty"`
}

// DocumentStatus defines model for Document.Status.
type DocumentStatus string

// DocumentPage defines model for DocumentPage.
type DocumentPage struct {
	HasMore    bool       `json:"has_more"`
	Items      []Document `json:"items"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// DocumentUpload defines model for DocumentUpload.
type DocumentUpload struct {
	File    openapi_types.File `json:"file"`
	Service *string            `json:"service,omitempty"`
	Tags    *[]string          `json:"tags,omitempty"`
}

// KnowledgeBase defines model for KnowledgeBase.
type KnowledgeBase struct {
	CreatedAt time.Time           `json:"created_at"`
	FolderUid string              `json:"folder_uid"`
	Id        BusinessID          `json:"id"`
	Name      string              `json:"name"`
	Status    KnowledgeBaseStatus `json:"status"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// KnowledgeBaseStatus defines model for KnowledgeBase.Status.
type KnowledgeBaseStatus string

// KnowledgeBasePage defines model for KnowledgeBasePage.
type KnowledgeBasePage struct {
	HasMore    bool            `json:"has_more"`
	Items      []KnowledgeBase `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// KnowledgeChunk defines model for KnowledgeChunk.
type KnowledgeChunk struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	DocumentId BusinessID `json:"document_id"`
	Id         string     `json:"id"`
	PageNumber int        `json:"page_number"`
	Position   string     `json:"position"`
	Text       string     `json:"text"`
}

// KnowledgeChunkPage defines model for KnowledgeChunkPage.
type KnowledgeChunkPage struct {
	HasMore    bool             `json:"has_more"`
	Items      []KnowledgeChunk `json:"items"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// KnowledgeCitation defines model for KnowledgeCitation.
type KnowledgeCitation struct {
	DocumentId BusinessID `json:"document_id"`
	PageNumber int        `json:"page_number"`
	Position   string     `json:"position"`
	SourceName string     `json:"source_name"`
}

// KnowledgeSearchHit defines model for KnowledgeSearchHit.
type KnowledgeSearchHit struct {
	Citation KnowledgeCitation `json:"citation"`
	Score    float64           `json:"score"`
	Text     string            `json:"text"`
}

// KnowledgeSearchRequest defines model for KnowledgeSearchRequest.
type KnowledgeSearchRequest struct {
	KnowledgeBaseIds []BusinessID `json:"knowledge_base_ids"`
	Limit            *int         `json:"limit,omitempty"`
	Query            string       `json:"query"`
	Service          *string      `json:"service,omitempty"`
	Threshold        *float64     `json:"threshold,omitempty"`
}

// KnowledgeSearchResponse defines model for KnowledgeSearchResponse.
type KnowledgeSearchResponse struct {
	Hits []KnowledgeSearchHit `json:"hits"`
}

// Message defines model for Message.
type Message struct {
	Content   string      `json:"content"`
	CreatedAt time.Time   `json:"created_at"`
	Id        BusinessID  `json:"id"`
	Role      MessageRole `json:"role"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// PageMetadata defines model for PageMetadata.
type PageMetadata struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Playbook defines model for Playbook.
type Playbook struct {
	Description string         `json:"description"`
	Id          BusinessID     `json:"id"`
	Name        string         `json:"name"`
	Source      string         `json:"source"`
	Status      PlaybookStatus `json:"status"`
}

// PlaybookStatus defines model for Playbook.Status.
type PlaybookStatus string

// PlaybookApprovalDecision defines model for PlaybookApprovalDecision.
type PlaybookApprovalDecision struct {
	Decision PlaybookApprovalDecisionDecision `json:"decision"`
	Inputs   *map[string]string               `json:"inputs,omitempty"`
}

// PlaybookApprovalDecisionDecision defines model for PlaybookApprovalDecision.Decision.
type PlaybookApprovalDecisionDecision string

// PlaybookPage defines model for PlaybookPage.
type PlaybookPage struct {
	HasMore    bool              `json:"has_more"`
	Items      []PlaybookSummary `json:"items"`
	NextCursor *string           `json:"next_cursor,omitempty"`
}

// PlaybookRun defines model for PlaybookRun.
type PlaybookRun struct {
	EndedAt    *time.Time        `json:"ended_at,omitempty"`
	Id         BusinessID        `json:"id"`
	PlaybookId BusinessID        `json:"playbook_id"`
	Sequence   int64             `json:"sequence"`
	StartedAt  time.Time         `json:"started_at"`
	Status     PlaybookRunStatus `json:"status"`
	Steps      *[]PlaybookStep   `json:"steps,omitempty"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

// PlaybookRunStatus defines model for PlaybookRun.Status.
type PlaybookRunStatus string

// PlaybookRunPage defines model for PlaybookRunPage.
type PlaybookRunPage struct {
	HasMore    bool          `json:"has_more"`
	Items      []PlaybookRun `json:"items"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

// PlaybookStep defines model for PlaybookStep.
type PlaybookStep struct {
	Approval  *map[string]interface{} `json:"approval,omitempty"`
	EndedAt   *time.Time              `json:"ended_at,omitempty"`
	HumanTask *map[string]interface{} `json:"human_task,omitempty"`
	Id        string                  `json:"id"`
	Name      string                  `json:"name"`
	StartedAt *time.Time              `json:"started_at,omitempty"`
	Status    PlaybookStepStatus      `json:"status"`
}

// PlaybookStepStatus defines model for PlaybookStep.Status.
type PlaybookStepStatus string

// PlaybookSummary defines model for PlaybookSummary.
type PlaybookSummary struct {
	Description string                `json:"description"`
	Id          BusinessID            `json:"id"`
	Name        string                `json:"name"`
	Status      PlaybookSummaryStatus `json:"status"`
}

// PlaybookSummaryStatus defines model for PlaybookSummary.Status.
type PlaybookSummaryStatus string

// Problem defines model for Problem.
type Problem struct {
	Code      ProblemCode `json:"code"`
	Detail    *string     `json:"detail,omitempty"`
	RequestId string      `json:"request_id"`
	Retryable *bool       `json:"retryable,omitempty"`
	Status    int         `json:"status"`
	Title     string      `json:"title"`
	TraceId   string      `json:"trace_id"`
	Type      string      `json:"type"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// QueryDefinition defines model for QueryDefinition.
type QueryDefinition struct {
	CreatedAt     time.Time  `json:"created_at"`
	DatasourceUid string     `json:"datasource_uid"`
	Expression    string     `json:"expression"`
	Id            BusinessID `json:"id"`
	Range         struct {
		From        time.Time `json:"from"`
		StepSeconds int64     `json:"step_seconds"`
		To          time.Time `json:"to"`
	} `json:"range"`
	Version int64 `json:"version"`
}

// ServiceEntry defines model for ServiceEntry.
type ServiceEntry struct {
	FolderUid string             `json:"folder_uid"`
	Id        BusinessID         `json:"id"`
	Labels    *map[string]string `json:"labels,omitempty"`
	Name      string             `json:"name"`
}

// ServicePage defines model for ServicePage.
type ServicePage struct {
	HasMore    bool           `json:"has_more"`
	Items      []ServiceEntry `json:"items"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`

	// FolderUid Request authorization context only; Agent Providers do not persist this value.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	FolderUid *string       `json:"folder_uid,omitempty"`
	Id        BusinessID    `json:"id"`
	Status    SessionStatus `json:"status"`
	Title     string        `json:"title"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// SessionStatus defines model for Session.Status.
type SessionStatus string

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	Messages *[]Message `json:"messages,omitempty"`
	Session  Session    `json:"session"`
}

// SessionPage defines model for SessionPage.
type SessionPage struct {
	HasMore    bool      `json:"has_more"`
	Items      []Session `json:"items"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// StartPlaybookRunRequest defines model for StartPlaybookRunRequest.
type StartPlaybookRunRequest struct {
	Parameters *map[string]string `json:"parameters,omitempty"`
}

// StartTurnRequest defines model for StartTurnRequest.
type StartTurnRequest struct {
	Mentions *[]string `json:"mentions,omitempty"`
	Message  string    `json:"message"`
}

// UpdateCanvasRequest defines model for UpdateCanvasRequest.
type UpdateCanvasRequest struct {
	ActiveChartId   *BusinessID               `json:"active_chart_id"`
	Layout          UpdateCanvasRequestLayout `json:"layout"`
	OrderedChartIds []BusinessID              `json:"ordered_chart_ids"`
	Visible         bool                      `json:"visible"`
}

// UpdateCanvasRequestLayout defines model for UpdateCanvasRequest.Layout.
type UpdateCanvasRequestLayout string

// UpdateDocumentRequest defines model for UpdateDocumentRequest.
type UpdateDocumentRequest struct {
	Service string   `json:"service"`
	Tags    []string `json:"tags"`
}

// UpdateKnowledgeBaseRequest defines model for UpdateKnowledgeBaseRequest.
type UpdateKnowledgeBaseRequest struct {
	Name   string                           `json:"name"`
	Status UpdateKnowledgeBaseRequestStatus `json:"status"`
}

// UpdateKnowledgeBaseRequestStatus defines model for UpdateKnowledgeBaseRequest.Status.
type UpdateKnowledgeBaseRequestStatus string

// UpdateSessionRequest defines model for UpdateSessionRequest.
type UpdateSessionRequest struct {
	Status *UpdateSessionRequestStatus `json:"status,omitempty"`
	Title  *string                     `json:"title,omitempty"`
}

// UpdateSessionRequestStatus defines model for UpdateSessionRequest.Status.
type UpdateSessionRequestStatus string

// ValidationResult defines model for ValidationResult.
type ValidationResult struct {
	Errors []struct {
		Message string  `json:"message"`
		Path    *string `json:"path,omitempty"`
	} `json:"errors"`
	Valid bool `json:"valid"`
}

// ApprovalID defines model for ApprovalID.
type ApprovalID = BusinessID

// ArtifactPath defines model for ArtifactPath.
type ArtifactPath = string

// CanvasRevision defines model for CanvasRevision.
type CanvasRevision = string

// Cursor defines model for Cursor.
type Cursor = string

// DocumentID defines model for DocumentID.
type DocumentID = BusinessID

// FolderUID defines model for FolderUID.
type FolderUID = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// KnowledgeBaseID defines model for KnowledgeBaseID.
type KnowledgeBaseID = BusinessID

// Limit defines model for Limit.
type Limit = int

// PlaybookID defines model for PlaybookID.
type PlaybookID = BusinessID

// RunID defines model for RunID.
type RunID = BusinessID

// SessionID defines model for SessionID.
type SessionID = BusinessID

// SessionStatusFilter defines model for SessionStatusFilter.
type SessionStatusFilter string

// StepID defines model for StepID.
type StepID = string

// TurnID defines model for TurnID.
type TurnID = BusinessID

// ListKnowledgeBasesParams defines parameters for ListKnowledgeBases.
type ListKnowledgeBasesParams struct {
	FolderUid *FolderUID `form:"folder_uid,omitempty" json:"folder_uid,omitempty"`
	Cursor    *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateKnowledgeBaseParams defines parameters for CreateKnowledgeBase.
type CreateKnowledgeBaseParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateDocumentParams defines parameters for CreateDocument.
type CreateDocumentParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListDocumentChunksParams defines parameters for ListDocumentChunks.
type ListDocumentChunksParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPlaybooksParams defines parameters for ListPlaybooks.
type ListPlaybooksParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePlaybookParams defines parameters for CreatePlaybook.
type CreatePlaybookParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListPlaybookRunsParams defines parameters for ListPlaybookRuns.
type ListPlaybookRunsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// StartPlaybookRunParams defines parameters for StartPlaybookRun.
type StartPlaybookRunParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ResolvePlaybookApprovalParams defines parameters for ResolvePlaybookApproval.
type ResolvePlaybookApprovalParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// DownloadPlaybookArtifactParams defines parameters for DownloadPlaybookArtifact.
type DownloadPlaybookArtifactParams struct {
	Path ArtifactPath `form:"path" json:"path"`
}

// PreviewPlaybookArtifactParams defines parameters for PreviewPlaybookArtifact.
type PreviewPlaybookArtifactParams struct {
	Path ArtifactPath `form:"path" json:"path"`
}

// StreamPlaybookRunEventsParams defines parameters for StreamPlaybookRunEvents.
type StreamPlaybookRunEventsParams struct {
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
}

// CompletePlaybookHumanTaskJSONBody defines parameters for CompletePlaybookHumanTask.
type CompletePlaybookHumanTaskJSONBody map[string]interface{}

// CompletePlaybookHumanTaskParams defines parameters for CompletePlaybookHumanTask.
type CompletePlaybookHumanTaskParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RetryPlaybookRunParams defines parameters for RetryPlaybookRun.
type RetryPlaybookRunParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	FolderUid *FolderUID `form:"folder_uid,omitempty" json:"folder_uid,omitempty"`
	Cursor    *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	Cursor *Cursor                   `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit                    `form:"limit,omitempty" json:"limit,omitempty"`
	Status *ListSessionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListSessionsParamsStatus defines parameters for ListSessions.
type ListSessionsParamsStatus string

// CreateSessionParams defines parameters for CreateSession.
type CreateSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ResolveAgentApprovalParams defines parameters for ResolveAgentApproval.
type ResolveAgentApprovalParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateSessionCanvasParams defines parameters for UpdateSessionCanvas.
type UpdateSessionCanvasParams struct {
	IfMatch CanvasRevision `json:"If-Match"`
}

// CancelTurnParams defines parameters for CancelTurn.
type CancelTurnParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// StartTurnParams defines parameters for StartTurn.
type StartTurnParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateKnowledgeBaseJSONRequestBody defines body for CreateKnowledgeBase for application/json ContentType.
type CreateKnowledgeBaseJSONRequestBody = CreateKnowledgeBaseRequest

// UpdateKnowledgeBaseJSONRequestBody defines body for UpdateKnowledgeBase for application/json ContentType.
type UpdateKnowledgeBaseJSONRequestBody = UpdateKnowledgeBaseRequest

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// CreateDocumentMultipartRequestBody defines body for CreateDocument for multipart/form-data ContentType.
type CreateDocumentMultipartRequestBody = DocumentUpload

// UpdateDocumentJSONRequestBody defines body for UpdateDocument for application/json ContentType.
type UpdateDocumentJSONRequestBody = UpdateDocumentRequest

// SearchKnowledgeJSONRequestBody defines body for SearchKnowledge for application/json ContentType.
type SearchKnowledgeJSONRequestBody = KnowledgeSearchRequest

// StartPlaybookRunJSONRequestBody defines body for StartPlaybookRun for application/json ContentType.
type StartPlaybookRunJSONRequestBody = StartPlaybookRunRequest

// ResolvePlaybookApprovalJSONRequestBody defines body for ResolvePlaybookApproval for application/json ContentType.
type ResolvePlaybookApprovalJSONRequestBody = PlaybookApprovalDecision

// CompletePlaybookHumanTaskJSONRequestBody defines body for CompletePlaybookHumanTask for application/json ContentType.
type CompletePlaybookHumanTaskJSONRequestBody CompletePlaybookHumanTaskJSONBody

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// UpdateSessionJSONRequestBody defines body for UpdateSession for application/json ContentType.
type UpdateSessionJSONRequestBody = UpdateSessionRequest

// ResolveAgentApprovalJSONRequestBody defines body for ResolveAgentApproval for application/json ContentType.
type ResolveAgentApprovalJSONRequestBody = ApprovalDecision

// UpdateSessionCanvasJSONRequestBody defines body for UpdateSessionCanvas for application/json ContentType.
type UpdateSessionCanvasJSONRequestBody = UpdateCanvasRequest

// StartTurnJSONRequestBody defines body for StartTurn for application/json ContentType.
type StartTurnJSONRequestBody = StartTurnRequest
