// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiv1

import (
	"time"
)

// Defines values for ApprovalDecisionDecision.
const (
	Approved ApprovalDecisionDecision = "approved"
	Rejected ApprovalDecisionDecision = "rejected"
)

// Valid indicates whether the value is a known member of the ApprovalDecisionDecision enum.
func (e ApprovalDecisionDecision) Valid() bool {
	switch e {
	case Approved:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityName.
const (
	CapabilityNameAgent        CapabilityName = "agent"
	CapabilityNameGrafanaRead  CapabilityName = "grafana_read"
	CapabilityNameGrafanaWrite CapabilityName = "grafana_write"
	CapabilityNameKnowledge    CapabilityName = "knowledge"
	CapabilityNamePlaybook     CapabilityName = "playbook"
)

// Valid indicates whether the value is a known member of the CapabilityName enum.
func (e CapabilityName) Valid() bool {
	switch e {
	case CapabilityNameAgent:
		return true
	case CapabilityNameGrafanaRead:
		return true
	case CapabilityNameGrafanaWrite:
		return true
	case CapabilityNameKnowledge:
		return true
	case CapabilityNamePlaybook:
		return true
	default:
		return false
	}
}

// Defines values for CapabilityStatus.
const (
	Available   CapabilityStatus = "available"
	Degraded    CapabilityStatus = "degraded"
	Unavailable CapabilityStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the CapabilityStatus enum.
func (e CapabilityStatus) Valid() bool {
	switch e {
	case Available:
		return true
	case Degraded:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for DocumentStatus.
const (
	DocumentStatusDisabled DocumentStatus = "disabled"
	DocumentStatusFailed   DocumentStatus = "failed"
	DocumentStatusIndexing DocumentStatus = "indexing"
	DocumentStatusPending  DocumentStatus = "pending"
	DocumentStatusReady    DocumentStatus = "ready"
)

// Valid indicates whether the value is a known member of the DocumentStatus enum.
func (e DocumentStatus) Valid() bool {
	switch e {
	case DocumentStatusDisabled:
		return true
	case DocumentStatusFailed:
		return true
	case DocumentStatusIndexing:
		return true
	case DocumentStatusPending:
		return true
	case DocumentStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for KnowledgeBaseStatus.
const (
	KnowledgeBaseStatusActive   KnowledgeBaseStatus = "active"
	KnowledgeBaseStatusDisabled KnowledgeBaseStatus = "disabled"
)

// Valid indicates whether the value is a known member of the KnowledgeBaseStatus enum.
func (e KnowledgeBaseStatus) Valid() bool {
	switch e {
	case KnowledgeBaseStatusActive:
		return true
	case KnowledgeBaseStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	Tool      MessageRole = "tool"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookStatus.
const (
	PlaybookStatusActive   PlaybookStatus = "active"
	PlaybookStatusDisabled PlaybookStatus = "disabled"
)

// Valid indicates whether the value is a known member of the PlaybookStatus enum.
func (e PlaybookStatus) Valid() bool {
	switch e {
	case PlaybookStatusActive:
		return true
	case PlaybookStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookApprovalDecisionDecision.
const (
	Approve PlaybookApprovalDecisionDecision = "approve"
	Reject  PlaybookApprovalDecisionDecision = "reject"
	Rewind  PlaybookApprovalDecisionDecision = "rewind"
)

// Valid indicates whether the value is a known member of the PlaybookApprovalDecisionDecision enum.
func (e PlaybookApprovalDecisionDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Reject:
		return true
	case Rewind:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookRunStatus.
const (
	PlaybookRunStatusCancelled          PlaybookRunStatus = "cancelled"
	PlaybookRunStatusFailed             PlaybookRunStatus = "failed"
	PlaybookRunStatusQueued             PlaybookRunStatus = "queued"
	PlaybookRunStatusRunning            PlaybookRunStatus = "running"
	PlaybookRunStatusSucceeded          PlaybookRunStatus = "succeeded"
	PlaybookRunStatusWaitingForApproval PlaybookRunStatus = "waiting_for_approval"
	PlaybookRunStatusWaitingForInput    PlaybookRunStatus = "waiting_for_input"
)

// Valid indicates whether the value is a known member of the PlaybookRunStatus enum.
func (e PlaybookRunStatus) Valid() bool {
	switch e {
	case PlaybookRunStatusCancelled:
		return true
	case PlaybookRunStatusFailed:
		return true
	case PlaybookRunStatusQueued:
		return true
	case PlaybookRunStatusRunning:
		return true
	case PlaybookRunStatusSucceeded:
		return true
	case PlaybookRunStatusWaitingForApproval:
		return true
	case PlaybookRunStatusWaitingForInput:
		return true
	default:
		return false
	}
}

// Defines values for PlaybookStepStatus.
const (
	PlaybookStepStatusCancelled          PlaybookStepStatus = "cancelled"
	PlaybookStepStatusFailed             PlaybookStepStatus = "failed"
	PlaybookStepStatusQueued             PlaybookStepStatus = "queued"
	PlaybookStepStatusRunning            PlaybookStepStatus = "running"
	PlaybookStepStatusSucceeded          PlaybookStepStatus = "succeeded"
	PlaybookStepStatusWaitingForApproval PlaybookStepStatus = "waiting_for_approval"
	PlaybookStepStatusWaitingForInput    PlaybookStepStatus = "waiting_for_input"
)

// Valid indicates whether the value is a known member of the PlaybookStepStatus enum.
func (e PlaybookStepStatus) Valid() bool {
	switch e {
	case PlaybookStepStatusCancelled:
		return true
	case PlaybookStepStatusFailed:
		return true
	case PlaybookStepStatusQueued:
		return true
	case PlaybookStepStatusRunning:
		return true
	case PlaybookStepStatusSucceeded:
		return true
	case PlaybookStepStatusWaitingForApproval:
		return true
	case PlaybookStepStatusWaitingForInput:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	CapabilityUnavailable ProblemCode = "capability_unavailable"
	Conflict              ProblemCode = "conflict"
	Forbidden             ProblemCode = "forbidden"
	Internal              ProblemCode = "internal"
	InvalidArgument       ProblemCode = "invalid_argument"
	NotFound              ProblemCode = "not_found"
	ProviderTimeout       ProblemCode = "provider_timeout"
	ProviderUnavailable   ProblemCode = "provider_unavailable"
	Unauthenticated       ProblemCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case CapabilityUnavailable:
		return true
	case Conflict:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case InvalidArgument:
		return true
	case NotFound:
		return true
	case ProviderTimeout:
		return true
	case ProviderUnavailable:
		return true
	case Unauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusActive   SessionStatus = "active"
	SessionStatusArchived SessionStatus = "archived"
	SessionStatusBusy     SessionStatus = "busy"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusActive:
		return true
	case SessionStatusArchived:
		return true
	case SessionStatusBusy:
		return true
	default:
		return false
	}
}

// Defines values for UpdateSessionRequestStatus.
const (
	UpdateSessionRequestStatusActive   UpdateSessionRequestStatus = "active"
	UpdateSessionRequestStatusArchived UpdateSessionRequestStatus = "archived"
)

// Valid indicates whether the value is a known member of the UpdateSessionRequestStatus enum.
func (e UpdateSessionRequestStatus) Valid() bool {
	switch e {
	case UpdateSessionRequestStatusActive:
		return true
	case UpdateSessionRequestStatusArchived:
		return true
	default:
		return false
	}
}

// ApprovalDecision defines model for ApprovalDecision.
type ApprovalDecision struct {
	Decision ApprovalDecisionDecision `json:"decision"`
	Reason   *string                  `json:"reason,omitempty"`
}

// ApprovalDecisionDecision defines model for ApprovalDecision.Decision.
type ApprovalDecisionDecision string

// Artifact defines model for Artifact.
type Artifact struct {
	MediaType string `json:"media_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
}

// ArtifactPreview defines model for ArtifactPreview.
type ArtifactPreview struct {
	MediaType string `json:"media_type"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Size      int64  `json:"size"`
	Text      string `json:"text"`
	Truncated bool   `json:"truncated"`
}

// BusinessID defines model for BusinessID.
type BusinessID = string

// Capability defines model for Capability.
type Capability struct {
	Name   CapabilityName   `json:"name"`
	Reason *string          `json:"reason,omitempty"`
	Status CapabilityStatus `json:"status"`
}

// CapabilityName defines model for Capability.Name.
type CapabilityName string

// CapabilityStatus defines model for Capability.Status.
type CapabilityStatus string

// CapabilityList defines model for CapabilityList.
type CapabilityList struct {
	Items []Capability `json:"items"`
}

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	MediaType string `json:"media_type"`
	Name      string `json:"name"`

	// UploadToken Short-lived Aegis upload token; never a Provider credential.
	UploadToken string `json:"upload_token"`
}

// CreateKnowledgeBaseRequest defines model for CreateKnowledgeBaseRequest.
type CreateKnowledgeBaseRequest struct {
	FolderUid string `json:"folder_uid"`
	Name      string `json:"name"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	FolderUid *string `json:"folder_uid,omitempty"`
	Title     string  `json:"title"`
}

// Document defines model for Document.
type Document struct {
	CreatedAt       time.Time      `json:"created_at"`
	Id              BusinessID     `json:"id"`
	KnowledgeBaseId BusinessID     `json:"knowledge_base_id"`
	MediaType       string         `json:"media_type"`
	Name            string         `json:"name"`
	Status          DocumentStatus `json:"status"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

// DocumentStatus defines model for Document.Status.
type DocumentStatus string

// DocumentPage defines model for DocumentPage.
type DocumentPage struct {
	HasMore    bool       `json:"has_more"`
	Items      []Document `json:"items"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// KnowledgeBase defines model for KnowledgeBase.
type KnowledgeBase struct {
	CreatedAt time.Time           `json:"created_at"`
	FolderUid string              `json:"folder_uid"`
	Id        BusinessID          `json:"id"`
	Name      string              `json:"name"`
	Status    KnowledgeBaseStatus `json:"status"`
	UpdatedAt time.Time           `json:"updated_at"`
}

// KnowledgeBaseStatus defines model for KnowledgeBase.Status.
type KnowledgeBaseStatus string

// KnowledgeBasePage defines model for KnowledgeBasePage.
type KnowledgeBasePage struct {
	HasMore    bool            `json:"has_more"`
	Items      []KnowledgeBase `json:"items"`
	NextCursor *string         `json:"next_cursor,omitempty"`
}

// Message defines model for Message.
type Message struct {
	Content   string      `json:"content"`
	CreatedAt time.Time   `json:"created_at"`
	Id        BusinessID  `json:"id"`
	Role      MessageRole `json:"role"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// PageMetadata defines model for PageMetadata.
type PageMetadata struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Playbook defines model for Playbook.
type Playbook struct {
	FolderUid *string        `json:"folder_uid,omitempty"`
	Id        BusinessID     `json:"id"`
	Name      string         `json:"name"`
	Source    *string        `json:"source,omitempty"`
	Status    PlaybookStatus `json:"status"`
}

// PlaybookStatus defines model for Playbook.Status.
type PlaybookStatus string

// PlaybookApprovalDecision defines model for PlaybookApprovalDecision.
type PlaybookApprovalDecision struct {
	Decision PlaybookApprovalDecisionDecision `json:"decision"`
	Inputs   *map[string]string               `json:"inputs,omitempty"`
}

// PlaybookApprovalDecisionDecision defines model for PlaybookApprovalDecision.Decision.
type PlaybookApprovalDecisionDecision string

// PlaybookPage defines model for PlaybookPage.
type PlaybookPage struct {
	HasMore    bool       `json:"has_more"`
	Items      []Playbook `json:"items"`
	NextCursor *string    `json:"next_cursor,omitempty"`
}

// PlaybookRun defines model for PlaybookRun.
type PlaybookRun struct {
	EndedAt    *time.Time        `json:"ended_at,omitempty"`
	Id         BusinessID        `json:"id"`
	PlaybookId BusinessID        `json:"playbook_id"`
	Sequence   int64             `json:"sequence"`
	StartedAt  time.Time         `json:"started_at"`
	Status     PlaybookRunStatus `json:"status"`
	Steps      *[]PlaybookStep   `json:"steps,omitempty"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

// PlaybookRunStatus defines model for PlaybookRun.Status.
type PlaybookRunStatus string

// PlaybookStep defines model for PlaybookStep.
type PlaybookStep struct {
	Approval  *map[string]interface{} `json:"approval,omitempty"`
	EndedAt   *time.Time              `json:"ended_at,omitempty"`
	HumanTask *map[string]interface{} `json:"human_task,omitempty"`
	Id        string                  `json:"id"`
	Name      string                  `json:"name"`
	StartedAt *time.Time              `json:"started_at,omitempty"`
	Status    PlaybookStepStatus      `json:"status"`
}

// PlaybookStepStatus defines model for PlaybookStep.Status.
type PlaybookStepStatus string

// Problem defines model for Problem.
type Problem struct {
	Code      ProblemCode `json:"code"`
	Detail    *string     `json:"detail,omitempty"`
	RequestId string      `json:"request_id"`
	Retryable *bool       `json:"retryable,omitempty"`
	Status    int         `json:"status"`
	Title     string      `json:"title"`
	TraceId   string      `json:"trace_id"`
	Type      string      `json:"type"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// ServiceEntry defines model for ServiceEntry.
type ServiceEntry struct {
	FolderUid string             `json:"folder_uid"`
	Id        BusinessID         `json:"id"`
	Labels    *map[string]string `json:"labels,omitempty"`
	Name      string             `json:"name"`
}

// ServicePage defines model for ServicePage.
type ServicePage struct {
	HasMore    bool           `json:"has_more"`
	Items      []ServiceEntry `json:"items"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time     `json:"created_at"`
	FolderUid *string       `json:"folder_uid,omitempty"`
	Id        BusinessID    `json:"id"`
	Status    SessionStatus `json:"status"`
	Title     string        `json:"title"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// SessionStatus defines model for Session.Status.
type SessionStatus string

// SessionDetail defines model for SessionDetail.
type SessionDetail struct {
	Messages *[]Message `json:"messages,omitempty"`
	Session  Session    `json:"session"`
}

// SessionPage defines model for SessionPage.
type SessionPage struct {
	HasMore    bool      `json:"has_more"`
	Items      []Session `json:"items"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// StartPlaybookRunRequest defines model for StartPlaybookRunRequest.
type StartPlaybookRunRequest struct {
	Parameters *map[string]string `json:"parameters,omitempty"`
}

// StartTurnRequest defines model for StartTurnRequest.
type StartTurnRequest struct {
	Mentions *[]string `json:"mentions,omitempty"`
	Message  string    `json:"message"`
}

// UpdateSessionRequest defines model for UpdateSessionRequest.
type UpdateSessionRequest struct {
	Status *UpdateSessionRequestStatus `json:"status,omitempty"`
	Title  *string                     `json:"title,omitempty"`
}

// UpdateSessionRequestStatus defines model for UpdateSessionRequest.Status.
type UpdateSessionRequestStatus string

// ValidationResult defines model for ValidationResult.
type ValidationResult struct {
	Errors []struct {
		Message string  `json:"message"`
		Path    *string `json:"path,omitempty"`
	} `json:"errors"`
	Valid bool `json:"valid"`
}

// ApprovalID defines model for ApprovalID.
type ApprovalID = BusinessID

// ArtifactPath defines model for ArtifactPath.
type ArtifactPath = string

// Cursor defines model for Cursor.
type Cursor = string

// FolderUID defines model for FolderUID.
type FolderUID = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// KnowledgeBaseID defines model for KnowledgeBaseID.
type KnowledgeBaseID = BusinessID

// Limit defines model for Limit.
type Limit = int

// PlaybookID defines model for PlaybookID.
type PlaybookID = BusinessID

// RunID defines model for RunID.
type RunID = BusinessID

// SessionID defines model for SessionID.
type SessionID = BusinessID

// StepID defines model for StepID.
type StepID = string

// ListKnowledgeBasesParams defines parameters for ListKnowledgeBases.
type ListKnowledgeBasesParams struct {
	FolderUid *FolderUID `form:"folder_uid,omitempty" json:"folder_uid,omitempty"`
	Cursor    *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateKnowledgeBaseParams defines parameters for CreateKnowledgeBase.
type CreateKnowledgeBaseParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateDocumentParams defines parameters for CreateDocument.
type CreateDocumentParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListPlaybooksParams defines parameters for ListPlaybooks.
type ListPlaybooksParams struct {
	FolderUid *FolderUID `form:"folder_uid,omitempty" json:"folder_uid,omitempty"`
	Cursor    *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePlaybookParams defines parameters for CreatePlaybook.
type CreatePlaybookParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// StartPlaybookRunParams defines parameters for StartPlaybookRun.
type StartPlaybookRunParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ResolvePlaybookApprovalParams defines parameters for ResolvePlaybookApproval.
type ResolvePlaybookApprovalParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// DownloadPlaybookArtifactParams defines parameters for DownloadPlaybookArtifact.
type DownloadPlaybookArtifactParams struct {
	Path ArtifactPath `form:"path" json:"path"`
}

// PreviewPlaybookArtifactParams defines parameters for PreviewPlaybookArtifact.
type PreviewPlaybookArtifactParams struct {
	Path ArtifactPath `form:"path" json:"path"`
}

// StreamPlaybookRunEventsParams defines parameters for StreamPlaybookRunEvents.
type StreamPlaybookRunEventsParams struct {
	AfterSequence *int64 `form:"after_sequence,omitempty" json:"after_sequence,omitempty"`
}

// CompletePlaybookHumanTaskJSONBody defines parameters for CompletePlaybookHumanTask.
type CompletePlaybookHumanTaskJSONBody map[string]interface{}

// CompletePlaybookHumanTaskParams defines parameters for CompletePlaybookHumanTask.
type CompletePlaybookHumanTaskParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RetryPlaybookRunParams defines parameters for RetryPlaybookRun.
type RetryPlaybookRunParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	FolderUid *FolderUID `form:"folder_uid,omitempty" json:"folder_uid,omitempty"`
	Cursor    *Cursor    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit     *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListSessionsParams defines parameters for ListSessions.
type ListSessionsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateSessionParams defines parameters for CreateSession.
type CreateSessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ResolveAgentApprovalParams defines parameters for ResolveAgentApproval.
type ResolveAgentApprovalParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// StartTurnParams defines parameters for StartTurn.
type StartTurnParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateKnowledgeBaseJSONRequestBody defines body for CreateKnowledgeBase for application/json ContentType.
type CreateKnowledgeBaseJSONRequestBody = CreateKnowledgeBaseRequest

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// StartPlaybookRunJSONRequestBody defines body for StartPlaybookRun for application/json ContentType.
type StartPlaybookRunJSONRequestBody = StartPlaybookRunRequest

// ResolvePlaybookApprovalJSONRequestBody defines body for ResolvePlaybookApproval for application/json ContentType.
type ResolvePlaybookApprovalJSONRequestBody = PlaybookApprovalDecision

// CompletePlaybookHumanTaskJSONRequestBody defines body for CompletePlaybookHumanTask for application/json ContentType.
type CompletePlaybookHumanTaskJSONRequestBody CompletePlaybookHumanTaskJSONBody

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// UpdateSessionJSONRequestBody defines body for UpdateSession for application/json ContentType.
type UpdateSessionJSONRequestBody = UpdateSessionRequest

// ResolveAgentApprovalJSONRequestBody defines body for ResolveAgentApproval for application/json ContentType.
type ResolveAgentApprovalJSONRequestBody = ApprovalDecision

// StartTurnJSONRequestBody defines body for StartTurn for application/json ContentType.
type StartTurnJSONRequestBody = StartTurnRequest
